apiVersion: v2
name: nginx
description: A simple nginx Helm chart for learning and practice
type: application
version: 0.1.0
appVersion: "1.25.2"
# Example dependency (used for the exercises below)
# To use: `helm repo add bitnami https://charts.bitnami.com/bitnami && helm dependency update charts/nginx`
dependencies:
  - name: redis
    version: "22.3.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
